version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  frontend:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
     - ./client:/client
  web:
    build: .
    command: ["./bin/docker-dev-server.sh"]
    volumes:
      - .:/my_app
    ports:
      - "3001:3001"
    depends_on:
      - db
      - frontend
