default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
#  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: my_app_development


test:
  <<: *default
  database: my_app_test
